// <auto-generated />
using System;
using AutoOA.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoOA.Core.Migrations
{
    [DbContext(typeof(AutoOADbContext))]
    [Migration("20221108001210_Test1")]
    partial class Test1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AutoOA.Core.BodyType", b =>
                {
                    b.Property<int>("BodyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BodyTypeId"), 1L, 1);

                    b.Property<string>("BodyTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BodyTypeId");

                    b.ToTable("BodyTypes");

                    b.HasData(
                        new
                        {
                            BodyTypeId = 1,
                            BodyTypeName = "Седан",
                            IconPath = "\\Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 2,
                            BodyTypeName = "Універсал",
                            IconPath = "\\Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 3,
                            BodyTypeName = "Хетчбек",
                            IconPath = "\\Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 4,
                            BodyTypeName = "Купе",
                            IconPath = "\\Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 5,
                            BodyTypeName = "Кабріолет",
                            IconPath = "\\Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 6,
                            BodyTypeName = "Позашляховик / Кросовер",
                            IconPath = "\\Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 7,
                            BodyTypeName = "Мінівен",
                            IconPath = "\\Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 8,
                            BodyTypeName = "Ліфтбек",
                            IconPath = "\\Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 9,
                            BodyTypeName = "Мікровен",
                            IconPath = "\\Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 10,
                            BodyTypeName = "Пікап",
                            IconPath = "\\Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 11,
                            BodyTypeName = "Родстер",
                            IconPath = "\\Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 12,
                            BodyTypeName = "Лімузин",
                            IconPath = "\\Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 13,
                            BodyTypeName = "Фастбек",
                            IconPath = "\\Images\\BodyTypeIcon.png"
                        });
                });

            modelBuilder.Entity("AutoOA.Core.DriveType", b =>
                {
                    b.Property<int>("DriveTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriveTypeId"), 1L, 1);

                    b.Property<string>("DriveTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DriveTypeId");

                    b.ToTable("DriveTypes");

                    b.HasData(
                        new
                        {
                            DriveTypeId = 1,
                            DriveTypeName = "Повний"
                        },
                        new
                        {
                            DriveTypeId = 2,
                            DriveTypeName = "Передній"
                        },
                        new
                        {
                            DriveTypeId = 3,
                            DriveTypeName = "Задній"
                        });
                });

            modelBuilder.Entity("AutoOA.Core.FuelType", b =>
                {
                    b.Property<int>("FuelTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FuelTypeId"), 1L, 1);

                    b.Property<string>("FuelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FuelTypeId");

                    b.ToTable("FuelTypes");

                    b.HasData(
                        new
                        {
                            FuelTypeId = 1,
                            FuelName = "Дизель",
                            IconPath = "\\Images\\fuelTypeIcon.png"
                        },
                        new
                        {
                            FuelTypeId = 2,
                            FuelName = "Бензин",
                            IconPath = "\\Images\\fuelTypeIcon.png"
                        },
                        new
                        {
                            FuelTypeId = 3,
                            FuelName = "Газ",
                            IconPath = "\\Images\\fuelTypeIcon.png"
                        },
                        new
                        {
                            FuelTypeId = 4,
                            FuelName = "Газ / Бензин",
                            IconPath = "\\Images\\fuelTypeIcon.png"
                        },
                        new
                        {
                            FuelTypeId = 5,
                            FuelName = "Гібрид",
                            IconPath = "\\Images\\fuelTypeIcon.png"
                        },
                        new
                        {
                            FuelTypeId = 6,
                            FuelName = "Електро",
                            IconPath = "\\Images\\fuelTypeIcon.png"
                        },
                        new
                        {
                            FuelTypeId = 7,
                            FuelName = "Інше",
                            IconPath = "\\Images\\fuelTypeIcon.png"
                        },
                        new
                        {
                            FuelTypeId = 8,
                            FuelName = "Газ метан",
                            IconPath = "\\Images\\fuelTypeIcon.png"
                        },
                        new
                        {
                            FuelTypeId = 9,
                            FuelName = "Газ пропан-бутан",
                            IconPath = "\\Images\\fuelTypeIcon.png"
                        });
                });

            modelBuilder.Entity("AutoOA.Core.GearBox", b =>
                {
                    b.Property<int>("GearBoxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GearBoxId"), 1L, 1);

                    b.Property<string>("GearBoxName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GearBoxId");

                    b.ToTable("GearBoxes");

                    b.HasData(
                        new
                        {
                            GearBoxId = 1,
                            GearBoxName = "Ручна / Механіка",
                            IconPath = "\\Images\\gearBoxIcon.png"
                        },
                        new
                        {
                            GearBoxId = 2,
                            GearBoxName = "Автомат",
                            IconPath = "\\Images\\gearBoxIcon.png"
                        },
                        new
                        {
                            GearBoxId = 3,
                            GearBoxName = "Типтронік",
                            IconPath = "\\Images\\gearBoxIcon.png"
                        },
                        new
                        {
                            GearBoxId = 4,
                            GearBoxName = "Робот",
                            IconPath = "\\Images\\gearBoxIcon.png"
                        },
                        new
                        {
                            GearBoxId = 5,
                            GearBoxName = "Варіатор",
                            IconPath = "\\Images\\gearBoxIcon.png"
                        });
                });

            modelBuilder.Entity("AutoOA.Core.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionId"), 1L, 1);

                    b.Property<string>("RegionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegionId");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            RegionId = 1,
                            RegionName = "Ukraine"
                        });
                });

            modelBuilder.Entity("AutoOA.Core.SalesData", b =>
                {
                    b.Property<int>("SalesDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalesDataId"), 1L, 1);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("SalesDataId");

                    b.HasIndex("VehicleId")
                        .IsUnique();

                    b.ToTable("SalesData");

                    b.HasData(
                        new
                        {
                            SalesDataId = 1,
                            CreatedOn = new DateTime(2022, 11, 8, 2, 12, 10, 489, DateTimeKind.Local).AddTicks(1810),
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = 1
                        },
                        new
                        {
                            SalesDataId = 2,
                            CreatedOn = new DateTime(2022, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = 2
                        });
                });

            modelBuilder.Entity("AutoOA.Core.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8baca772-a11d-4870-962a-4a180d49b885",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "20adee1b-9966-4a9b-bbf8-e1babaa9feee",
                            Email = "admin@autooa.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@AUTOOA.COM",
                            NormalizedUserName = "ADMIN@AUTOOA.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEL4Bk67v8BOpxM+ALZwlpoqDvav61Go9QDmTaN0HnmU80ppprnOiBQRfWG25HjtW2w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b697a210-5277-401b-b1de-2adaf3565110",
                            TwoFactorEnabled = false,
                            UserName = "admin@autooa.com"
                        },
                        new
                        {
                            Id = "36d1babf-d86e-43f3-b9b4-3deb3ece53fb",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5c2a680b-2ff8-42f3-95ed-887f30044993",
                            Email = "moder@autooa.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MODER@AUTOOA.COM",
                            NormalizedUserName = "MODER@AUTOOA.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEOBHSlA92Zg3j8FPet++P/QBnoNtsBCFerSacBY2QARrk464TC0PmoibO2rIqRfgOg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "62607cb5-1bae-4304-828f-ef73e6349158",
                            TwoFactorEnabled = false,
                            UserName = "moder@autooa.com"
                        },
                        new
                        {
                            Id = "9a0ebf61-9bdc-426b-8019-1cbd34fce1e9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1a0a9697-09dd-4bd6-b4dc-c15e9cdd9596",
                            Email = "user@autooa.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@AUTOOA.COM",
                            NormalizedUserName = "USER@AUTOOA.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEAlMjUyCMpY8qFTzbY1iGjkliSN4OB5R9E69SB7DgRsC9e3tBSGH4bkCNjrkzYL6zA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a1770aee-0faf-4874-943a-247956e0fcd9",
                            TwoFactorEnabled = false,
                            UserName = "user@autooa.com"
                        });
                });

            modelBuilder.Entity("AutoOA.Core.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"), 1L, 1);

                    b.Property<int>("BodyTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DriveTypeId")
                        .HasColumnType("int");

                    b.Property<int>("FuelTypeId")
                        .HasColumnType("int");

                    b.Property<int>("GearBoxId")
                        .HasColumnType("int");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("MileageIconPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfDoors")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.Property<decimal>("Price_EUR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price_UAH")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price_USD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<short>("ProductionYear")
                        .HasColumnType("smallint");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("StateNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VehicleIconPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleModelId")
                        .HasColumnType("int");

                    b.Property<bool>("isNew")
                        .HasColumnType("bit");

                    b.HasKey("VehicleId");

                    b.HasIndex("BodyTypeId");

                    b.HasIndex("DriveTypeId");

                    b.HasIndex("FuelTypeId");

                    b.HasIndex("GearBoxId");

                    b.HasIndex("RegionId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleModelId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            BodyTypeId = 1,
                            Color = "Black",
                            Description = "Авто в дуже хорошому стані. Повністтю обслужене. Капіталовкладень не потребує.",
                            DriveTypeId = 1,
                            FuelTypeId = 1,
                            GearBoxId = 1,
                            Mileage = 90000,
                            MileageIconPath = "\\Images\\MileageIcon.png",
                            NumberOfDoors = 5,
                            NumberOfSeats = 4,
                            Price_EUR = 18968.65m,
                            Price_UAH = 698187.11m,
                            Price_USD = 19000m,
                            ProductionYear = (short)2006,
                            RegionId = 1,
                            StateNumber = "Не задано",
                            UserId = "9a0ebf61-9bdc-426b-8019-1cbd34fce1e9",
                            VehicleIconPath = "\\Images\\w220cidan.png",
                            VehicleModelId = 1,
                            isNew = true
                        },
                        new
                        {
                            VehicleId = 2,
                            BodyTypeId = 2,
                            Color = "Gray",
                            Description = "Продаю свій автомобіль у хорошому стані. Зроблено всі планові роботи, все працює добре. Є невеликі подряпини, пов'язані з експлуатацією.",
                            DriveTypeId = 3,
                            FuelTypeId = 2,
                            GearBoxId = 2,
                            Mileage = 320000,
                            MileageIconPath = "\\Images\\MileageIcon.png",
                            NumberOfDoors = 5,
                            NumberOfSeats = 4,
                            Price_EUR = 14976.07m,
                            Price_UAH = 551200.35m,
                            Price_USD = 15000m,
                            ProductionYear = (short)2000,
                            RegionId = 1,
                            StateNumber = "Не задано",
                            UserId = "9a0ebf61-9bdc-426b-8019-1cbd34fce1e9",
                            VehicleIconPath = "\\Images\\320Universal.png",
                            VehicleModelId = 2,
                            isNew = false
                        });
                });

            modelBuilder.Entity("AutoOA.Core.VehicleBrand", b =>
                {
                    b.Property<int>("VehicleBrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleBrandId"), 1L, 1);

                    b.Property<string>("VehicleBrandName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleBrandId");

                    b.ToTable("VehicleBrands");

                    b.HasData(
                        new
                        {
                            VehicleBrandId = 1,
                            VehicleBrandName = "Mercedes"
                        },
                        new
                        {
                            VehicleBrandId = 2,
                            VehicleBrandName = "BMW"
                        });
                });

            modelBuilder.Entity("AutoOA.Core.VehicleModel", b =>
                {
                    b.Property<int>("VehicleModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleModelId"), 1L, 1);

                    b.Property<int>("VehicleBrandId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleModelName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleModelId");

                    b.HasIndex("VehicleBrandId");

                    b.ToTable("VehicleModels");

                    b.HasData(
                        new
                        {
                            VehicleModelId = 1,
                            VehicleBrandId = 1,
                            VehicleModelName = "E 220"
                        },
                        new
                        {
                            VehicleModelId = 2,
                            VehicleBrandId = 2,
                            VehicleModelName = "320"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c874f5fb-70fd-405e-99fa-a3c712a9da02",
                            ConcurrencyStamp = "e3a4af1b-53be-4345-b228-3ec0a82eb200",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "0e0b2ff0-80c3-4e22-a99a-d88bca2893f9",
                            ConcurrencyStamp = "d15b0aad-0658-41ba-8edd-23323e835f01",
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = "9a1f0b64-db5d-456d-9c7a-9a8af59c7b79",
                            ConcurrencyStamp = "891e04af-bde2-46a8-acf1-af6d7e8053f0",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "8baca772-a11d-4870-962a-4a180d49b885",
                            RoleId = "c874f5fb-70fd-405e-99fa-a3c712a9da02"
                        },
                        new
                        {
                            UserId = "8baca772-a11d-4870-962a-4a180d49b885",
                            RoleId = "0e0b2ff0-80c3-4e22-a99a-d88bca2893f9"
                        },
                        new
                        {
                            UserId = "8baca772-a11d-4870-962a-4a180d49b885",
                            RoleId = "9a1f0b64-db5d-456d-9c7a-9a8af59c7b79"
                        },
                        new
                        {
                            UserId = "36d1babf-d86e-43f3-b9b4-3deb3ece53fb",
                            RoleId = "0e0b2ff0-80c3-4e22-a99a-d88bca2893f9"
                        },
                        new
                        {
                            UserId = "36d1babf-d86e-43f3-b9b4-3deb3ece53fb",
                            RoleId = "9a1f0b64-db5d-456d-9c7a-9a8af59c7b79"
                        },
                        new
                        {
                            UserId = "9a0ebf61-9bdc-426b-8019-1cbd34fce1e9",
                            RoleId = "9a1f0b64-db5d-456d-9c7a-9a8af59c7b79"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AutoOA.Core.SalesData", b =>
                {
                    b.HasOne("AutoOA.Core.Vehicle", "Vehicle")
                        .WithOne("SalesData")
                        .HasForeignKey("AutoOA.Core.SalesData", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoOA.Core.Vehicle", b =>
                {
                    b.HasOne("AutoOA.Core.BodyType", "BodyType")
                        .WithMany("Vehicle")
                        .HasForeignKey("BodyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoOA.Core.DriveType", "DriveType")
                        .WithMany("Vehicle")
                        .HasForeignKey("DriveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoOA.Core.FuelType", "FuelType")
                        .WithMany("Vehicle")
                        .HasForeignKey("FuelTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoOA.Core.GearBox", "GearBox")
                        .WithMany("Vehicle")
                        .HasForeignKey("GearBoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoOA.Core.Region", "Region")
                        .WithMany("Vehicles")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoOA.Core.User", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("UserId");

                    b.HasOne("AutoOA.Core.VehicleModel", "VehicleModel")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodyType");

                    b.Navigation("DriveType");

                    b.Navigation("FuelType");

                    b.Navigation("GearBox");

                    b.Navigation("Region");

                    b.Navigation("User");

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("AutoOA.Core.VehicleModel", b =>
                {
                    b.HasOne("AutoOA.Core.VehicleBrand", "VehicleBrand")
                        .WithMany("VehicleModels")
                        .HasForeignKey("VehicleBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleBrand");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AutoOA.Core.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AutoOA.Core.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoOA.Core.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AutoOA.Core.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoOA.Core.BodyType", b =>
                {
                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoOA.Core.DriveType", b =>
                {
                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoOA.Core.FuelType", b =>
                {
                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoOA.Core.GearBox", b =>
                {
                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoOA.Core.Region", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("AutoOA.Core.User", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("AutoOA.Core.Vehicle", b =>
                {
                    b.Navigation("SalesData");
                });

            modelBuilder.Entity("AutoOA.Core.VehicleBrand", b =>
                {
                    b.Navigation("VehicleModels");
                });

            modelBuilder.Entity("AutoOA.Core.VehicleModel", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
