// <auto-generated />
using System;
using AutoOA.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoOA.Core.Migrations
{
    [DbContext(typeof(AutoOADbContext))]
    [Migration("20221020233341_Test1")]
    partial class Test1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AutoOA.Core.BodyType", b =>
                {
                    b.Property<int>("BodyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BodyTypeId"), 1L, 1);

                    b.Property<string>("BodyTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BodyTypeId");

                    b.ToTable("BodyTypes");

                    b.HasData(
                        new
                        {
                            BodyTypeId = 1,
                            BodyTypeName = "Седан",
                            IconPath = "Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 2,
                            BodyTypeName = "Універсал",
                            IconPath = "Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 3,
                            BodyTypeName = "Хетчбек",
                            IconPath = "Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 4,
                            BodyTypeName = "Купе",
                            IconPath = "Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 5,
                            BodyTypeName = "Кабріолет",
                            IconPath = "Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 6,
                            BodyTypeName = "Позашляховик / Кросовер",
                            IconPath = "Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 7,
                            BodyTypeName = "Мінівен",
                            IconPath = "Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 8,
                            BodyTypeName = "Ліфтбек",
                            IconPath = "Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 9,
                            BodyTypeName = "Мікровен",
                            IconPath = "Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 10,
                            BodyTypeName = "Пікап",
                            IconPath = "Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 11,
                            BodyTypeName = "Родстер",
                            IconPath = "Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 12,
                            BodyTypeName = "Лімузин",
                            IconPath = "Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 13,
                            BodyTypeName = "Фастбек",
                            IconPath = "Images\\BodyTypeIcon.png"
                        });
                });

            modelBuilder.Entity("AutoOA.Core.DriveType", b =>
                {
                    b.Property<int>("DriveTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriveTypeId"), 1L, 1);

                    b.Property<string>("DriveTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DriveTypeId");

                    b.ToTable("DriveTypes");

                    b.HasData(
                        new
                        {
                            DriveTypeId = 1,
                            DriveTypeName = "Повний"
                        },
                        new
                        {
                            DriveTypeId = 2,
                            DriveTypeName = "Передній"
                        },
                        new
                        {
                            DriveTypeId = 3,
                            DriveTypeName = "Задній"
                        });
                });

            modelBuilder.Entity("AutoOA.Core.FuelType", b =>
                {
                    b.Property<int>("FuelTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FuelTypeId"), 1L, 1);

                    b.Property<string>("FuelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FuelTypeId");

                    b.ToTable("FuelTypes");

                    b.HasData(
                        new
                        {
                            FuelTypeId = 1,
                            FuelName = "Дизель",
                            IconPath = "Images\\fuelTypeIcon.png"
                        },
                        new
                        {
                            FuelTypeId = 2,
                            FuelName = "Бензин",
                            IconPath = "Images\\fuelTypeIcon.png"
                        },
                        new
                        {
                            FuelTypeId = 3,
                            FuelName = "Газ",
                            IconPath = "Images\\fuelTypeIcon.png"
                        },
                        new
                        {
                            FuelTypeId = 4,
                            FuelName = "Газ / Бензин",
                            IconPath = "Images\\fuelTypeIcon.png"
                        },
                        new
                        {
                            FuelTypeId = 5,
                            FuelName = "Гібрид",
                            IconPath = "Images\\fuelTypeIcon.png"
                        },
                        new
                        {
                            FuelTypeId = 6,
                            FuelName = "Електро",
                            IconPath = "Images\\fuelTypeIcon.png"
                        },
                        new
                        {
                            FuelTypeId = 7,
                            FuelName = "Інше",
                            IconPath = "Images\\fuelTypeIcon.png"
                        },
                        new
                        {
                            FuelTypeId = 8,
                            FuelName = "Газ метан",
                            IconPath = "Images\\fuelTypeIcon.png"
                        },
                        new
                        {
                            FuelTypeId = 9,
                            FuelName = "Газ пропан-бутан",
                            IconPath = "Images\\fuelTypeIcon.png"
                        });
                });

            modelBuilder.Entity("AutoOA.Core.GearBox", b =>
                {
                    b.Property<int>("GearBoxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GearBoxId"), 1L, 1);

                    b.Property<string>("GearBoxName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GearBoxId");

                    b.ToTable("GearBoxes");

                    b.HasData(
                        new
                        {
                            GearBoxId = 1,
                            GearBoxName = "Ручна / Механіка",
                            IconPath = "Images\\gearBoxIcon.png"
                        },
                        new
                        {
                            GearBoxId = 2,
                            GearBoxName = "Автомат",
                            IconPath = "Images\\gearBoxIcon.png"
                        },
                        new
                        {
                            GearBoxId = 3,
                            GearBoxName = "Типтронік",
                            IconPath = "Images\\gearBoxIcon.png"
                        },
                        new
                        {
                            GearBoxId = 4,
                            GearBoxName = "Робот",
                            IconPath = "Images\\gearBoxIcon.png"
                        },
                        new
                        {
                            GearBoxId = 5,
                            GearBoxName = "Варіатор",
                            IconPath = "Images\\gearBoxIcon.png"
                        });
                });

            modelBuilder.Entity("AutoOA.Core.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8974e59e-38e3-4d85-82e0-33cbb5217a3d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b7ca9d83-7aa7-4d68-a4d9-f1e99854996b",
                            Email = "admin@autooa.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@AUTOOA.COM",
                            NormalizedUserName = "ADMIN@AUTOOA.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEF6vQ/l3Mg6QYf6iMJ572bkbuhDvSBJqALkabKwZ0ntvdJDSpRTM2Aw3rgMFT5w/yw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9dba61af-6ed5-4a6c-9177-47d1d273121a",
                            TwoFactorEnabled = false,
                            UserName = "admin@autooa.com"
                        },
                        new
                        {
                            Id = "c4676a5f-b7c6-420e-aa0d-f1a77426157a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "50145372-1329-401c-a601-d0be4615f5d1",
                            Email = "moder@autooa.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MODER@AUTOOA.COM",
                            NormalizedUserName = "MODER@AUTOOA.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEAWNk8l6GYN4EXlXapsRmOMQXmeaeP6vwNOX34RwodQo1XntOpWYXqfTnARj/iKcOw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0852bc1c-ad57-44ed-b1b8-b749a2e30671",
                            TwoFactorEnabled = false,
                            UserName = "moder@autooa.com"
                        },
                        new
                        {
                            Id = "54440f44-252c-4531-8d56-a2a1e6d6e50a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f1d4da5f-227a-4719-ab22-83fbdc3fb2cf",
                            Email = "user@autooa.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@AUTOOA.COM",
                            NormalizedUserName = "USER@AUTOOA.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEOCUN3pApsyORIt023hguk1uzcorLkdcKKPylu2EXe5UBHAUOSwEfI5FTPQi/AOwfA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7847fb4c-1a25-4113-ad47-8b122d1dec38",
                            TwoFactorEnabled = false,
                            UserName = "user@autooa.com"
                        });
                });

            modelBuilder.Entity("AutoOA.Core.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"), 1L, 1);

                    b.Property<int>("BodyTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DriveTypeId")
                        .HasColumnType("int");

                    b.Property<int>("FuelTypeId")
                        .HasColumnType("int");

                    b.Property<int>("GearBoxId")
                        .HasColumnType("int");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("MileageIconPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleIconPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleModelId")
                        .HasColumnType("int");

                    b.Property<bool>("isNew")
                        .HasColumnType("bit");

                    b.HasKey("VehicleId");

                    b.HasIndex("BodyTypeId");

                    b.HasIndex("DriveTypeId");

                    b.HasIndex("FuelTypeId");

                    b.HasIndex("GearBoxId");

                    b.HasIndex("VehicleModelId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            BodyTypeId = 1,
                            Color = "Black",
                            Description = "Авто в дуже хорошому стані. Повністтю обслужене. Капіталовкладень не потребує.",
                            DriveTypeId = 1,
                            FuelTypeId = 1,
                            GearBoxId = 1,
                            Mileage = 90000,
                            MileageIconPath = "Images\\MileageIcon.png",
                            Price = 15000m,
                            ProductionDate = new DateTime(2006, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleIconPath = "\\Images\\w220cidan.png",
                            VehicleModelId = 1,
                            isNew = true
                        },
                        new
                        {
                            VehicleId = 2,
                            BodyTypeId = 2,
                            Color = "Gray",
                            Description = "Продаю свій автомобіль у хорошому стані. Зроблено всі планові роботи, все працює добре. Є невеликі подряпини, пов'язані з експлуатацією.",
                            DriveTypeId = 3,
                            FuelTypeId = 2,
                            GearBoxId = 2,
                            Mileage = 320000,
                            MileageIconPath = "Images\\MileageIcon.png",
                            Price = 9000m,
                            ProductionDate = new DateTime(2000, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleIconPath = "\\Images\\320Universal.png",
                            VehicleModelId = 2,
                            isNew = false
                        });
                });

            modelBuilder.Entity("AutoOA.Core.VehicleBrand", b =>
                {
                    b.Property<int>("VehicleBrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleBrandId"), 1L, 1);

                    b.Property<string>("VehicleBrandName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleBrandId");

                    b.ToTable("VehicleBrands");

                    b.HasData(
                        new
                        {
                            VehicleBrandId = 1,
                            VehicleBrandName = "Mercedes"
                        },
                        new
                        {
                            VehicleBrandId = 2,
                            VehicleBrandName = "BMW"
                        });
                });

            modelBuilder.Entity("AutoOA.Core.VehicleModel", b =>
                {
                    b.Property<int>("VehicleModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleModelId"), 1L, 1);

                    b.Property<int>("VehicleBrandId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleModelName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleModelId");

                    b.HasIndex("VehicleBrandId");

                    b.ToTable("VehicleModels");

                    b.HasData(
                        new
                        {
                            VehicleModelId = 1,
                            VehicleBrandId = 1,
                            VehicleModelName = "E 220"
                        },
                        new
                        {
                            VehicleModelId = 2,
                            VehicleBrandId = 2,
                            VehicleModelName = "320"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1d8ac350-0590-4973-b3da-eb0daab1b6ca",
                            ConcurrencyStamp = "4e421d61-094a-49ba-a880-976648fcdf93",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "737d13d4-54b3-47d9-bcc2-f2fc1df0c9d7",
                            ConcurrencyStamp = "15522d6d-2e7e-4938-a3f0-1ac355a5c94d",
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = "fdb16792-5366-4650-8af9-acc9b615f3d6",
                            ConcurrencyStamp = "0538504f-54b7-4301-8c11-c5913a31f342",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "8974e59e-38e3-4d85-82e0-33cbb5217a3d",
                            RoleId = "1d8ac350-0590-4973-b3da-eb0daab1b6ca"
                        },
                        new
                        {
                            UserId = "8974e59e-38e3-4d85-82e0-33cbb5217a3d",
                            RoleId = "737d13d4-54b3-47d9-bcc2-f2fc1df0c9d7"
                        },
                        new
                        {
                            UserId = "8974e59e-38e3-4d85-82e0-33cbb5217a3d",
                            RoleId = "fdb16792-5366-4650-8af9-acc9b615f3d6"
                        },
                        new
                        {
                            UserId = "c4676a5f-b7c6-420e-aa0d-f1a77426157a",
                            RoleId = "737d13d4-54b3-47d9-bcc2-f2fc1df0c9d7"
                        },
                        new
                        {
                            UserId = "c4676a5f-b7c6-420e-aa0d-f1a77426157a",
                            RoleId = "fdb16792-5366-4650-8af9-acc9b615f3d6"
                        },
                        new
                        {
                            UserId = "54440f44-252c-4531-8d56-a2a1e6d6e50a",
                            RoleId = "fdb16792-5366-4650-8af9-acc9b615f3d6"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AutoOA.Core.Vehicle", b =>
                {
                    b.HasOne("AutoOA.Core.BodyType", "BodyType")
                        .WithMany("Vehicle")
                        .HasForeignKey("BodyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoOA.Core.DriveType", "DriveType")
                        .WithMany("Vehicle")
                        .HasForeignKey("DriveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoOA.Core.FuelType", "FuelType")
                        .WithMany("Vehicle")
                        .HasForeignKey("FuelTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoOA.Core.GearBox", "GearBox")
                        .WithMany("Vehicle")
                        .HasForeignKey("GearBoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoOA.Core.VehicleModel", "VehicleModel")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodyType");

                    b.Navigation("DriveType");

                    b.Navigation("FuelType");

                    b.Navigation("GearBox");

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("AutoOA.Core.VehicleModel", b =>
                {
                    b.HasOne("AutoOA.Core.VehicleBrand", "VehicleBrand")
                        .WithMany("VehicleModels")
                        .HasForeignKey("VehicleBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleBrand");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AutoOA.Core.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AutoOA.Core.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoOA.Core.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AutoOA.Core.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoOA.Core.BodyType", b =>
                {
                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoOA.Core.DriveType", b =>
                {
                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoOA.Core.FuelType", b =>
                {
                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoOA.Core.GearBox", b =>
                {
                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoOA.Core.VehicleBrand", b =>
                {
                    b.Navigation("VehicleModels");
                });

            modelBuilder.Entity("AutoOA.Core.VehicleModel", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
