// <auto-generated />
using System;
using AutoOA.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoOA.Core.Migrations
{
    [DbContext(typeof(AutoOADbContext))]
    [Migration("20221206164549_Initial-Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AutoOA.Core.BodyType", b =>
                {
                    b.Property<int>("BodyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BodyTypeId"), 1L, 1);

                    b.Property<string>("BodyTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BodyTypeId");

                    b.ToTable("BodyTypes");

                    b.HasData(
                        new
                        {
                            BodyTypeId = 1,
                            BodyTypeName = "Седан",
                            IconPath = "\\Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 2,
                            BodyTypeName = "Універсал",
                            IconPath = "\\Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 3,
                            BodyTypeName = "Хетчбек",
                            IconPath = "\\Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 4,
                            BodyTypeName = "Купе",
                            IconPath = "\\Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 5,
                            BodyTypeName = "Кабріолет",
                            IconPath = "\\Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 6,
                            BodyTypeName = "Позашляховик / Кросовер",
                            IconPath = "\\Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 7,
                            BodyTypeName = "Мінівен",
                            IconPath = "\\Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 8,
                            BodyTypeName = "Ліфтбек",
                            IconPath = "\\Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 9,
                            BodyTypeName = "Мікровен",
                            IconPath = "\\Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 10,
                            BodyTypeName = "Пікап",
                            IconPath = "\\Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 11,
                            BodyTypeName = "Родстер",
                            IconPath = "\\Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 12,
                            BodyTypeName = "Лімузин",
                            IconPath = "\\Images\\BodyTypeIcon.png"
                        },
                        new
                        {
                            BodyTypeId = 13,
                            BodyTypeName = "Фастбек",
                            IconPath = "\\Images\\BodyTypeIcon.png"
                        });
                });

            modelBuilder.Entity("AutoOA.Core.DriveType", b =>
                {
                    b.Property<int>("DriveTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriveTypeId"), 1L, 1);

                    b.Property<string>("DriveTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DriveTypeId");

                    b.ToTable("DriveTypes");

                    b.HasData(
                        new
                        {
                            DriveTypeId = 1,
                            DriveTypeName = "Повний"
                        },
                        new
                        {
                            DriveTypeId = 2,
                            DriveTypeName = "Передній"
                        },
                        new
                        {
                            DriveTypeId = 3,
                            DriveTypeName = "Задній"
                        });
                });

            modelBuilder.Entity("AutoOA.Core.FuelType", b =>
                {
                    b.Property<int>("FuelTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FuelTypeId"), 1L, 1);

                    b.Property<string>("FuelTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FuelTypeId");

                    b.ToTable("FuelTypes");

                    b.HasData(
                        new
                        {
                            FuelTypeId = 1,
                            FuelTypeName = "Дизель",
                            IconPath = "\\Images\\fuelTypeIcon.png"
                        },
                        new
                        {
                            FuelTypeId = 2,
                            FuelTypeName = "Бензин",
                            IconPath = "\\Images\\fuelTypeIcon.png"
                        },
                        new
                        {
                            FuelTypeId = 3,
                            FuelTypeName = "Газ",
                            IconPath = "\\Images\\fuelTypeIcon.png"
                        },
                        new
                        {
                            FuelTypeId = 4,
                            FuelTypeName = "Газ / Бензин",
                            IconPath = "\\Images\\fuelTypeIcon.png"
                        },
                        new
                        {
                            FuelTypeId = 5,
                            FuelTypeName = "Гібрид",
                            IconPath = "\\Images\\fuelTypeIcon.png"
                        },
                        new
                        {
                            FuelTypeId = 6,
                            FuelTypeName = "Електро",
                            IconPath = "\\Images\\fuelTypeIcon.png"
                        },
                        new
                        {
                            FuelTypeId = 7,
                            FuelTypeName = "Інше",
                            IconPath = "\\Images\\fuelTypeIcon.png"
                        },
                        new
                        {
                            FuelTypeId = 8,
                            FuelTypeName = "Газ метан",
                            IconPath = "\\Images\\fuelTypeIcon.png"
                        },
                        new
                        {
                            FuelTypeId = 9,
                            FuelTypeName = "Газ пропан-бутан",
                            IconPath = "\\Images\\fuelTypeIcon.png"
                        });
                });

            modelBuilder.Entity("AutoOA.Core.GearBox", b =>
                {
                    b.Property<int>("GearBoxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GearBoxId"), 1L, 1);

                    b.Property<string>("GearBoxName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GearBoxId");

                    b.ToTable("GearBoxes");

                    b.HasData(
                        new
                        {
                            GearBoxId = 1,
                            GearBoxName = "Ручна / Механіка",
                            IconPath = "\\Images\\gearBoxIcon.png"
                        },
                        new
                        {
                            GearBoxId = 2,
                            GearBoxName = "Автомат",
                            IconPath = "\\Images\\gearBoxIcon.png"
                        },
                        new
                        {
                            GearBoxId = 3,
                            GearBoxName = "Типтронік",
                            IconPath = "\\Images\\gearBoxIcon.png"
                        },
                        new
                        {
                            GearBoxId = 4,
                            GearBoxName = "Робот",
                            IconPath = "\\Images\\gearBoxIcon.png"
                        },
                        new
                        {
                            GearBoxId = 5,
                            GearBoxName = "Варіатор",
                            IconPath = "\\Images\\gearBoxIcon.png"
                        });
                });

            modelBuilder.Entity("AutoOA.Core.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionId"), 1L, 1);

                    b.Property<string>("RegionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegionId");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            RegionId = 1,
                            RegionName = "Ukraine"
                        });
                });

            modelBuilder.Entity("AutoOA.Core.SalesData", b =>
                {
                    b.Property<int>("SalesDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalesDataId"), 1L, 1);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("SalesDataId");

                    b.HasIndex("VehicleId")
                        .IsUnique();

                    b.ToTable("SalesData");

                    b.HasData(
                        new
                        {
                            SalesDataId = 1,
                            CreatedOn = new DateTime(2022, 12, 6, 18, 45, 48, 298, DateTimeKind.Local).AddTicks(2414),
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = 1
                        },
                        new
                        {
                            SalesDataId = 2,
                            CreatedOn = new DateTime(2022, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = 2
                        });
                });

            modelBuilder.Entity("AutoOA.Core.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "827dedae-c632-4080-9575-a3d2b6b74896",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c8c7a00d-91b7-4710-8db3-f59decff659a",
                            Email = "admin@autooa.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@AUTOOA.COM",
                            NormalizedUserName = "ADMIN@AUTOOA.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEPxFV52qKCNLQR+V3sYcO0gqbcYOTfYol7+ZrxAgX9OAtFmWrmwxx8jzsdvilWefoA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f398c3f3-eed7-46a8-a1fd-f8fd7b073806",
                            TwoFactorEnabled = false,
                            UserName = "admin@autooa.com"
                        },
                        new
                        {
                            Id = "1a81a9a8-27e6-4736-b978-62c07f371f06",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8825754f-1196-426c-9f82-b35ca62c4e86",
                            Email = "moder@autooa.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MODER@AUTOOA.COM",
                            NormalizedUserName = "MODER@AUTOOA.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEFJVbLF7fAqaoBc74NJY/6pKix99mgg6r2CeK2WHO7F+l+BMwae34ockmHIbsH5IIA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ced73644-7b68-423d-924c-5e028ef34fd7",
                            TwoFactorEnabled = false,
                            UserName = "moder@autooa.com"
                        },
                        new
                        {
                            Id = "f8d520d2-9529-45ac-8a82-5eccb10da53c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6c923564-297e-4693-a7fa-e803911a13be",
                            Email = "user@autooa.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@AUTOOA.COM",
                            NormalizedUserName = "USER@AUTOOA.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEB2EhU3Ho+fB4BEmqQBaStfkMZcvwgNIzUN8ofhUopmjUxhJRPrpRfGrPb0NqQtr+w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "502bafeb-24d4-4f31-9c98-48c65904ffe7",
                            TwoFactorEnabled = false,
                            UserName = "user@autooa.com"
                        });
                });

            modelBuilder.Entity("AutoOA.Core.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"), 1L, 1);

                    b.Property<int>("BodyTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DriveTypeId")
                        .HasColumnType("int");

                    b.Property<int>("FuelTypeId")
                        .HasColumnType("int");

                    b.Property<int>("GearBoxId")
                        .HasColumnType("int");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("MileageIconPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfDoors")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.Property<decimal>("Price_EUR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price_UAH")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price_USD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<short>("ProductionYear")
                        .HasColumnType("smallint");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("StateNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VehicleIconPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleModelId")
                        .HasColumnType("int");

                    b.Property<bool>("isNew")
                        .HasColumnType("bit");

                    b.HasKey("VehicleId");

                    b.HasIndex("BodyTypeId");

                    b.HasIndex("DriveTypeId");

                    b.HasIndex("FuelTypeId");

                    b.HasIndex("GearBoxId");

                    b.HasIndex("RegionId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleModelId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            BodyTypeId = 1,
                            Color = "Black",
                            Description = "Авто в дуже хорошому стані. Повністтю обслужене. Капіталовкладень не потребує.",
                            DriveTypeId = 1,
                            FuelTypeId = 1,
                            GearBoxId = 1,
                            Mileage = 90000,
                            MileageIconPath = "\\Images\\MileageIcon.png",
                            NumberOfDoors = 5,
                            NumberOfSeats = 4,
                            Price_EUR = 18968.65m,
                            Price_UAH = 698187.11m,
                            Price_USD = 19000m,
                            ProductionYear = (short)2006,
                            RegionId = 1,
                            StateNumber = "Не задано",
                            UserId = "f8d520d2-9529-45ac-8a82-5eccb10da53c",
                            VehicleIconPath = "\\Images\\w220cidan.png",
                            VehicleModelId = 1,
                            isNew = true
                        },
                        new
                        {
                            VehicleId = 2,
                            BodyTypeId = 2,
                            Color = "Gray",
                            Description = "Продаю свій автомобіль у хорошому стані. Зроблено всі планові роботи, все працює добре. Є невеликі подряпини, пов'язані з експлуатацією.",
                            DriveTypeId = 3,
                            FuelTypeId = 2,
                            GearBoxId = 2,
                            Mileage = 320000,
                            MileageIconPath = "\\Images\\MileageIcon.png",
                            NumberOfDoors = 5,
                            NumberOfSeats = 4,
                            Price_EUR = 14976.07m,
                            Price_UAH = 551200.35m,
                            Price_USD = 15000m,
                            ProductionYear = (short)2000,
                            RegionId = 1,
                            StateNumber = "Не задано",
                            UserId = "f8d520d2-9529-45ac-8a82-5eccb10da53c",
                            VehicleIconPath = "\\Images\\320Universal.png",
                            VehicleModelId = 2,
                            isNew = false
                        });
                });

            modelBuilder.Entity("AutoOA.Core.VehicleBrand", b =>
                {
                    b.Property<int>("VehicleBrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleBrandId"), 1L, 1);

                    b.Property<string>("VehicleBrandName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleBrandId");

                    b.ToTable("VehicleBrands");

                    b.HasData(
                        new
                        {
                            VehicleBrandId = 1,
                            VehicleBrandName = "Mercedes"
                        },
                        new
                        {
                            VehicleBrandId = 2,
                            VehicleBrandName = "Bmw"
                        },
                        new
                        {
                            VehicleBrandId = 3,
                            VehicleBrandName = "Acura"
                        },
                        new
                        {
                            VehicleBrandId = 4,
                            VehicleBrandName = "Alfa Romeo"
                        },
                        new
                        {
                            VehicleBrandId = 5,
                            VehicleBrandName = "Alphina"
                        },
                        new
                        {
                            VehicleBrandId = 6,
                            VehicleBrandName = "Audi"
                        });
                });

            modelBuilder.Entity("AutoOA.Core.VehicleModel", b =>
                {
                    b.Property<int>("VehicleModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleModelId"), 1L, 1);

                    b.Property<int>("VehicleBrandId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleModelName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleModelId");

                    b.HasIndex("VehicleBrandId");

                    b.ToTable("VehicleModels");

                    b.HasData(
                        new
                        {
                            VehicleModelId = 1,
                            VehicleBrandId = 1,
                            VehicleModelName = "E 220"
                        },
                        new
                        {
                            VehicleModelId = 2,
                            VehicleBrandId = 2,
                            VehicleModelName = "320"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "e61ea266-5003-4342-bd0f-1cf9d20f0e72",
                            ConcurrencyStamp = "e93a1127-3a4b-4b2d-9577-d3d055b8d74c",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "61d15afb-c563-4d9c-bd06-90923c86b3a4",
                            ConcurrencyStamp = "b113fa43-ea5e-4b94-ad74-595aed9a3441",
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = "20f90418-3c7b-4a11-86ab-7ba45e6691db",
                            ConcurrencyStamp = "e8ba005d-32d8-4bad-ae7d-97f1fcf1a665",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "827dedae-c632-4080-9575-a3d2b6b74896",
                            RoleId = "e61ea266-5003-4342-bd0f-1cf9d20f0e72"
                        },
                        new
                        {
                            UserId = "827dedae-c632-4080-9575-a3d2b6b74896",
                            RoleId = "61d15afb-c563-4d9c-bd06-90923c86b3a4"
                        },
                        new
                        {
                            UserId = "827dedae-c632-4080-9575-a3d2b6b74896",
                            RoleId = "20f90418-3c7b-4a11-86ab-7ba45e6691db"
                        },
                        new
                        {
                            UserId = "1a81a9a8-27e6-4736-b978-62c07f371f06",
                            RoleId = "61d15afb-c563-4d9c-bd06-90923c86b3a4"
                        },
                        new
                        {
                            UserId = "1a81a9a8-27e6-4736-b978-62c07f371f06",
                            RoleId = "20f90418-3c7b-4a11-86ab-7ba45e6691db"
                        },
                        new
                        {
                            UserId = "f8d520d2-9529-45ac-8a82-5eccb10da53c",
                            RoleId = "20f90418-3c7b-4a11-86ab-7ba45e6691db"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AutoOA.Core.SalesData", b =>
                {
                    b.HasOne("AutoOA.Core.Vehicle", "Vehicle")
                        .WithOne("SalesData")
                        .HasForeignKey("AutoOA.Core.SalesData", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoOA.Core.Vehicle", b =>
                {
                    b.HasOne("AutoOA.Core.BodyType", "BodyType")
                        .WithMany("Vehicle")
                        .HasForeignKey("BodyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoOA.Core.DriveType", "DriveType")
                        .WithMany("Vehicle")
                        .HasForeignKey("DriveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoOA.Core.FuelType", "FuelType")
                        .WithMany("Vehicle")
                        .HasForeignKey("FuelTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoOA.Core.GearBox", "GearBox")
                        .WithMany("Vehicle")
                        .HasForeignKey("GearBoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoOA.Core.Region", "Region")
                        .WithMany("Vehicle")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoOA.Core.User", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("UserId");

                    b.HasOne("AutoOA.Core.VehicleModel", "VehicleModel")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodyType");

                    b.Navigation("DriveType");

                    b.Navigation("FuelType");

                    b.Navigation("GearBox");

                    b.Navigation("Region");

                    b.Navigation("User");

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("AutoOA.Core.VehicleModel", b =>
                {
                    b.HasOne("AutoOA.Core.VehicleBrand", "VehicleBrand")
                        .WithMany("VehicleModels")
                        .HasForeignKey("VehicleBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleBrand");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AutoOA.Core.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AutoOA.Core.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoOA.Core.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AutoOA.Core.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoOA.Core.BodyType", b =>
                {
                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoOA.Core.DriveType", b =>
                {
                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoOA.Core.FuelType", b =>
                {
                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoOA.Core.GearBox", b =>
                {
                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoOA.Core.Region", b =>
                {
                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoOA.Core.User", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("AutoOA.Core.Vehicle", b =>
                {
                    b.Navigation("SalesData");
                });

            modelBuilder.Entity("AutoOA.Core.VehicleBrand", b =>
                {
                    b.Navigation("VehicleModels");
                });

            modelBuilder.Entity("AutoOA.Core.VehicleModel", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
